export const SAVE_USER='SAVE_USER';
export const REMOVE_USER='REMOVE_USER';
export const COURSE_ABS='COURSE_ABS';
export const GET_STORE='GET_STORE';
export const ADD_BOOKMARK='ADD_BOOKMARK';
export const REMOVE_BOOKMARK='REMOVE_BOOKMARK';
export const INIT_BOOKMARK='INIT_BOOKMARK';

export const ADD_CLOUD='ADD_CLOUD';
export const REMOVE_CLOUD='REMOVE_CLOUD';
export const EMPTY_FAVORITES='REMOVE_CLOUD';

export const ADD_BASKET='ADD_BASKET';
export const REMOVE_BASKET='REMOVE_BASKET';
export const EMPTY_BASKET='EMPTY_BASKET';
export const INC_PAGE='INC_PAGE';
export const DEC_PAGE='DEC_PAGE';
export const ADD_PRODUCTS='ADD_PRODUCTS';
export const INIT_PRODUCTS='INIT_PRODUCTS';
export const EMPTY_PRODUCTS='EMPTY_PRODUCTS';
export const SAVE_CATEGORIES='SAVE_CATEGORIES';
export const SAVE_MESSAGES='SAVE_MESSAGES';

